# Generated by Django 4.0.3 on 2022-03-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('about', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=2000)),
                ('overall_rating', models.IntegerField(default=0)),
                ('catagory', models.CharField(default='Computer Science', max_length=250)),
                ('platform', models.CharField(default='YouTube', max_length=1000)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=1000)),
                ('language', models.CharField(default='English', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=4)),
                ('certificate', models.BooleanField(default=False)),
                ('material_type', models.CharField(choices=[('Videos', 'Videos'), ('Textual', 'Textual'), ('Hybrid', 'Hybrid')], default='Videos', max_length=25)),
                ('added_by', models.CharField(default='Neesham', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Courses-sinx',
                'ordering': ['-overall_rating'],
            },
        ),
    ]
